namespace EduEngine.Editor
{
    internal static class KeyCodeExtentions
    {
        public static char ToChar(this KeyCode keyCode)
        {
            return keyCode switch
            {
                KeyCode.A => 'A',
                KeyCode.B => 'B',
                KeyCode.C => 'C',
                KeyCode.D => 'D',
                KeyCode.E => 'E',
                KeyCode.F => 'F',
                KeyCode.G => 'G',
                KeyCode.H => 'H',
                KeyCode.I => 'I',
                KeyCode.J => 'J',
                KeyCode.K => 'K',
                KeyCode.L => 'L',
                KeyCode.M => 'M',
                KeyCode.N => 'N',
                KeyCode.O => 'O',
                KeyCode.P => 'P',
                KeyCode.Q => 'Q',
                KeyCode.R => 'R',
                KeyCode.S => 'S',
                KeyCode.T => 'T',
                KeyCode.U => 'U',
                KeyCode.V => 'V',
                KeyCode.W => 'W',
                KeyCode.X => 'X',
                KeyCode.Y => 'Y',
                KeyCode.Z => 'Z',
                KeyCode.A1 => '1',
                KeyCode.A2 => '2',
                KeyCode.A3 => '3',
                KeyCode.A4 => '4',
                KeyCode.A5 => '5',
                KeyCode.A6 => '6',
                KeyCode.A7 => '7',
                KeyCode.A8 => '8',
                KeyCode.A9 => '9',
                KeyCode.A0 => '0',
                KeyCode.MINUS => '-',
                KeyCode.EQUALS => '=',
                KeyCode.SEMICOLON => ';',
                KeyCode.APOSTROPHE => '\'',
                KeyCode.GRAVE => '`',
                KeyCode.COMMA => ',',
                KeyCode.PERIOD => '.',
                KeyCode.SLASH => '/',
                KeyCode.BACKSLASH => '\\',
                KeyCode.SPACE => ' ',
                _ => '\0',
            };
        }
        
        public static ImGuiNET.ImGuiKey ToImGuiKey(this KeyCode keyCode)
        {
            return keyCode switch
            {
                KeyCode.A => ImGuiNET.ImGuiKey.A,
                KeyCode.B => ImGuiNET.ImGuiKey.B,
                KeyCode.C => ImGuiNET.ImGuiKey.C,
                KeyCode.D => ImGuiNET.ImGuiKey.D,
                KeyCode.E => ImGuiNET.ImGuiKey.E,
                KeyCode.F => ImGuiNET.ImGuiKey.F,
                KeyCode.G => ImGuiNET.ImGuiKey.G,
                KeyCode.H => ImGuiNET.ImGuiKey.H,
                KeyCode.I => ImGuiNET.ImGuiKey.I,
                KeyCode.J => ImGuiNET.ImGuiKey.J,
                KeyCode.K => ImGuiNET.ImGuiKey.K,
                KeyCode.L => ImGuiNET.ImGuiKey.L,
                KeyCode.M => ImGuiNET.ImGuiKey.M,
                KeyCode.N => ImGuiNET.ImGuiKey.N,
                KeyCode.O => ImGuiNET.ImGuiKey.O,
                KeyCode.P => ImGuiNET.ImGuiKey.P,
                KeyCode.Q => ImGuiNET.ImGuiKey.Q,
                KeyCode.R => ImGuiNET.ImGuiKey.R,
                KeyCode.S => ImGuiNET.ImGuiKey.S,
                KeyCode.T => ImGuiNET.ImGuiKey.T,
                KeyCode.U => ImGuiNET.ImGuiKey.U,
                KeyCode.V => ImGuiNET.ImGuiKey.V,
                KeyCode.W => ImGuiNET.ImGuiKey.W,
                KeyCode.X => ImGuiNET.ImGuiKey.X,
                KeyCode.Y => ImGuiNET.ImGuiKey.Y,
                KeyCode.Z => ImGuiNET.ImGuiKey.Z,
                KeyCode.A1 => ImGuiNET.ImGuiKey._1,
                KeyCode.A2 => ImGuiNET.ImGuiKey._2,
                KeyCode.A3 => ImGuiNET.ImGuiKey._3,
                KeyCode.A4 => ImGuiNET.ImGuiKey._4,
                KeyCode.A5 => ImGuiNET.ImGuiKey._5,
                KeyCode.A6 => ImGuiNET.ImGuiKey._6,
                KeyCode.A7 => ImGuiNET.ImGuiKey._7,
                KeyCode.A8 => ImGuiNET.ImGuiKey._8,
                KeyCode.A9 => ImGuiNET.ImGuiKey._9,
                KeyCode.A0 => ImGuiNET.ImGuiKey._0,
                KeyCode.SPACE => ImGuiNET.ImGuiKey.Space,
                KeyCode.RETURN => ImGuiNET.ImGuiKey.Enter,
                KeyCode.BACK => ImGuiNET.ImGuiKey.Backspace,
                KeyCode.TAB => ImGuiNET.ImGuiKey.Tab,
                KeyCode.LSHIFT => ImGuiNET.ImGuiKey.ModShift,
                KeyCode.RSHIFT => ImGuiNET.ImGuiKey.ModShift,
                KeyCode.LCONTROL => ImGuiNET.ImGuiKey.ModCtrl,
                KeyCode.RCONTROL => ImGuiNET.ImGuiKey.ModCtrl,
                KeyCode.LWIN => ImGuiNET.ImGuiKey.ModSuper,
                KeyCode.RWIN => ImGuiNET.ImGuiKey.ModSuper,
                KeyCode.LMENU => ImGuiNET.ImGuiKey.ModAlt,
                KeyCode.RMENU => ImGuiNET.ImGuiKey.ModAlt,
                KeyCode.UP => ImGuiNET.ImGuiKey.UpArrow,
                KeyCode.DOWN => ImGuiNET.ImGuiKey.DownArrow,
                KeyCode.LEFT => ImGuiNET.ImGuiKey.LeftArrow,
                KeyCode.RIGHT => ImGuiNET.ImGuiKey.RightArrow,
                KeyCode.ESCAPE => ImGuiNET.ImGuiKey.Escape,
                KeyCode.CAPITAL => ImGuiNET.ImGuiKey.CapsLock,
                _ => ImGuiNET.ImGuiKey.None
            };
        }
    }
}
